### ISSUE TITLE
No dSYM files found on iTunes Connect - this usually happens when no recompling happened yet

### ISSUE THREAD

**Issue by allen8300** [fastlane/fastlane#11755]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [dowload_dsyms with version: 'latest' does not download from the latest version](https://github.com/fastlane/fastlane/issues/10255)
- [x] I searched for [Fix download_dsyms.rb ‘latest’](https://github.com/fastlane/fastlane/pull/10337)
- [x] I searched for [download_dsyms(build_number) not downloading dSYMs](https://github.com/fastlane/fastlane/issues/6528)
- [x] I searched for [download_dsyms Platform not passing down To new TestFlight API](https://github.com/fastlane/fastlane/issues/10957)
- [x]  I searched for [Search for app version platform using symbol instead of string](https://github.com/fastlane/fastlane/pull/10984)

******But none of above really solves the problem.**

### Issue Description

I'm referring to doc: [https://docs.fastlane.tools/actions/download_dsyms/](url)
![screen shot 2018-02-01 at 10 17 21 am](https://user-images.githubusercontent.com/1751906/35657759-210b6d0a-0739-11e8-90f5-50296611e65e.png)

My app is already on AppsStore for sale;
I can also manually download dSYM from iTC successfully;

**But when I use following lane and specify version+build, it fails with error:**
![screen shot 2018-02-01 at 10 21 53 am](https://user-images.githubusercontent.com/1751906/35657888-c58e4c94-0739-11e8-9cf2-faeb8326536e.png)

Here's my lane in Fastfile:

lane :refresh_dsyms do
download_dsyms(version: "33.0", build_number: "888", platform: "ios")
end

<details>
  <pre>[
Driving the lane 'ios refresh_dsyms'
--- Step: download_dsyms ---
Login to iTunes Connect (xxxxx@xxx.com)
Login successful
Looking for dSYM files for com.xxx.xx  v32.0
No dSYM files found on iTunes Connect - this usually happens when no recompling happened yet
]</pre>
</details>

I have checked six similar issues that list at the top of this page, but none really hits the point.

### Environment
Here's output of "fastlane env"
<details>
  <pre>[
| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.79.0  | ✅ Up-To-Date  | 
| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.rbenv/versions/2.4.3/bin/fastlane        |
| Host                        | Mac OS X 10.12.6 (16G1114)                  |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.3/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2n  7 Dec 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |
]</pre>
</details>

**Comment by allen8300** [comment]
@fastlane-bot  Hey, env info is already pasted at the bottom of my issue.

**Comment by KrauseFx** [comment]
Thanks for submitting this. It seems like more users experience issues with this integration, I'll try to take a look at this today

**Comment by KrauseFx** [comment]
```
Looking for dSYM files for com.xxx.xx  v32.0
```
Seems like your version name contains a `v`? Can you try passing that in the action call also?

**Comment by allen8300** [comment]
@KrauseFx Hi man, that's log of fastlane;  my code is like this:
download_dsyms(version: "33.0", build_number: "888", platform: "ios")

**Comment by KrauseFx** [comment]
Try `version: "v33.0", build_number: ...`

**Comment by allen8300** [comment]
@KrauseFx , still the same error, man;
As I see, there must be something wrong with download_dsyms(Parameters);
Can you check your [source code](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/download_dsyms.rb)?

**Comment by yfldj** [comment]
have the same problem.

**Comment by allen8300** [comment]
@KrauseFx , hi man ,any good news?

**Comment by allen8300** [comment]
@KrauseFx ， anyone there?

**Comment by taquitos** [comment]
@allen8300, if you're able, would you be able to try out https://github.com/fastlane/fastlane/pull/11819 ? It won't fix anything, but hopefully there is enough logging enabled in there that the output from your console (after running it with `--verbose`) should help us figure out what is going on.

**Comment by allen8300** [comment]
@taquitos thx so much for replying man;

Here's detail log after running "fastlane myLaneName --verbose":

 
![2018212115230dama](https://user-images.githubusercontent.com/1751906/36083222-5236bcd0-0feb-11e8-9f32-7387c4b85ffb.png)

**Comment by KrauseFx** [comment]
@allen8300 are you sure this is running the PR @taquitos linked? Note that this hasn't been shipped as part of a _fastlane_ release yet, so you'll need to manually check out the branch and use the local version

**Comment by meccatol** [comment]
@allen8300 @KrauseFx 
Hello, i've used 'dowload_dsyms' action for downloading dSYMs of Builds of AppStore Versions.
In my iTunesConnect, There are some versions that available downloading dSYMs.

But inside of 'dowload_dsyms' action, it's look like only finding versions in TestFlight.
('app.all_build_train_numbers' is actually fetching TestFlight Versions.)

It's looked so weird. TestFlight version only available in 90 days after uploaded.
(i think it should try 'all_builds_for_train' of 'TunesClient'. am i something wrong? let me know. :D )
