### ISSUE TITLE
Updating fastlane from X.Y.Z to X.Z.Z doesn't actually update even though it says it does.

### ISSUE THREAD

**Issue by akwilliamson** [fastlane/fastlane#12877]
### New Issue Checklist

- [ ] Updated fastlane to the latest version (this is the problem)
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Updating fastlane via the command `update_fastlane` at the top of my `Fastfile` from Y to Z always says it's updating: "Updating Fastlane from X to Y...", pauses (making it feel like it's updating), then says it's done updating: "Finished updating fastlane" but it never actually updates it. I can run an identical fastlane lane immediately after and it will output the same message that it's updating to and from identical versions and "finish successfully".

##### Complete output when running fastlane, including the stack trace and command used
[10:11:27]: -----------------------------
[10:11:27]: --- Step: update_fastlane ---
[10:11:27]: -----------------------------
[10:11:27]: Looking for updates for fastlane...
[10:11:31]: Updating fastlane from 2.96.1 to 2.99.0... 🚀
[10:12:04]: Finished updating fastlane
[10:12:04]: Cleaning up old versions...
[10:12:04]: 
[10:12:04]: Please help us test early releases of fastlane by opting into nightly builds 🌃
[10:12:04]: Just replace your `update_fastlane` call with
[10:12:04]: 
[10:12:04]: ▸ update_fastlane(nightly: true)
[10:12:04]: 
[10:12:04]: Nightly builds are reviewed and tested just like the public releases 🚂
[10:12:04]: 
[10:12:04]: fastlane.tools successfully updated! I will now restart myself... 😴
...

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.5                                     |
| Ruby                        | 2.4.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.15.2 (Apple Git-101.1)        |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.13.5 (17F77)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.2_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.4.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
update_fastlane

default_platform :ios

platform :ios do

#####################################################################################################
#####################################################################################################
#####################################################################################################
#####################################################################################################
#####################################################################################################
# ---------------------------------------------------------------------------------------------------
# *************************************** FASTLANE VARIABLES ****************************************
# ---------------------------------------------------------------------------------------------------
#####################################################################################################
#####################################################################################################
#####################################################################################################
#####################################################################################################
#####################################################################################################

# REDACTED's repository dedicated to storing certificates and code signing credentials
# for each internal project. These credentials are shared between all team members.

  CERTS_REPO = "REDACTED"

# The branch used to store the credentials described in 'CERTS_REPO' for internal use. Each branch
# can store credentials for development (locally), ad-hoc (deployment through Fabric Beta),
# or distribution (deployment through Testflight or App Store via REDACTED's account).
# Whatever you choose to name this branch, you must create the branch manually off of the empty
# 'master' branch before Fastlane can use it. Fastlane will not create branches for you. Naming
# convention for an internal use branch is currently "{YOUR-PROJECT-NAME}-internal". Anybody using
# this repo through Fastlane must have access to the repo and/or branch in order for it to work.

  CERTS_INTERNAL_BRANCH = "REDACTED" # e.g. "coolproject-internal"

# The branch used to store the credentials described in 'CERTS_REPO' for the client. Each
# branch can store credentials for development (locally), ad-hoc (deployment through Fabric
# Beta), or distribution (deployment through Testflight or App Store via the client's account).
# Whatever you choose to name this branch, you must create the branch manually off of the empty
# 'master' branch before Fastlane can use it. Fastlane will not create branches for you. Naming
# convention for a client's account is currently "{YOUR-PROJECT-NAME}-release". Anybody using
# this repo through Fastlane must have access to the repo and/or branch in order for it to work.

  CERTS_CLIENT_BRANCH = "{PLACEHOLDER}" # e.g. "coolproject-release"

# The API Key for REDACTED's Fabric account. This value is used to to distribute builds
# through Fabric via Fastlane's Crashlytics tool. If Fabric is not being used, you can ignore
# this value. If you are using a client's Fabric account, you will need to aquire said client's
# Fabric API Key and replace this value. You still need to include the Crashlytics/Fabric SDKs
# in your project and associated setup as you would for any other project.

  FABRIC_API_KEY = ENV['FABRIC_API_KEY']

# The Build Secret for REDACTED's Fabric account. This value is used to to distribute
# builds through Fabric via Fastlane's Crashlytics tool. If Fabric is not being used, you can
# ignore this value. If you are using a client's Fabric account, you will need to aquire said
# client's Fabric Build Secret and replace this value. You still need to include the
# Crashlytics/Fabric SDKs in your project and associated setup as you would for any other project.

  FABRIC_BUILD_SECRET = ENV['FABRIC_SECRET']

# The username for REDACTED's Apple Developer Portal and iTunes Connect accounts used to
# log in to perform various tasks like producing provisioning profiles, syncing and storing
# certificates, and distributing builds through iTunes Connect. The 'REDACTED'
# account was created to share one login for the entire team to prevent exposing your own
# account credentials for others to use.

  INTERNAL_USERNAME  = "REDACTED"

# The team name for REDACTED's Apple Developer Portal. This is explicitly required when
# using multiple teams for a project. Since REDACTED's projects tend to be distributed and
# tested internally, and subsequently delivered to clients, we use multiple teams. This is used by
# a variety of tools to determine which team to create new App records in the Apple Developer
# portal as well as which team to distribute builds to via iTunes Connect.

  INTERNAL_TEAM_NAME = "REDACTED" # TODO: Possibly remove?REDACTED isn't connected to multiple teams...

# The team ID for REDACTED's Apple Developer Portal. This is explicitly required when
# using multiple teams for a project. Since REDACTED's projects tend to be distributed and
# tested internally, and subsequently delivered to clients, we use multiple teams. Used by the
# 'Match' tool for syncing/repairing/replacing certificates stored in 'CERTS_REPO' with those
# stored in the Apple Developer Portal associated with this team.

  INTERNAL_TEAM_ID = "REDACTED" # TODO: Possibly remove? REDACTED isn't connected to multiple teams...

# The bundle ID of the application. This is used to create app records in REDACTED's Apple
# Developer Portal and sync provisioning/code signing for said application. We also use this value
# to set the arbitrary SKU value required when creating app records. It's best practice to open the
# client's project in Xcode, see what their bundle identifier is, and replace their company name with
# 'REDACTED'. e.g: replace com.ClientCompanyName.coolproject with REDACTED

  INTERNAL_APP_ID = "REDACTED" # e.g. "REDACTEDt"

# Simply the name of the application. You could specify an app name for distribution internally
# through REDACTED's account for testing that is different than the app name distributed
# to the client.

  INTERNAL_APP_NAME = "REDACTED" # e.g. "Cool Project QA"

# The scheme of the app to build and archive for distribution. If you don't have any custom schemes
# then it's the name of the application.

  INTERNAL_SCHEME    = "REDACTED" # e.g. "Cool Project QA Release"

# The username for the client's Apple Developer Portal and iTunes Connect accounts used to
# log in to perform various tasks like producing provisioning profiles, syncing and storing
# certificates, and distributing builds through iTunes Connect. This could be your own
# username if the client gave you access to their account, or it could be a username that
# they provided for you.

  CLIENT_USERNAME  = "{PLACEHOLDER}" # e.g. "REDACTED"

# The team name for the client's Apple Developer Portal. This is explicitly required when deploying
# a project to multiple teams. Since REDACTED's projects tend to be distributed and
# tested internally, and subsequently delivered to clients, that exemplifies multiple teams. This is
# used by a variety of tools to determine which team to create new App records in the Apple Developer
# portal as well as which team to distribute builds to via iTunes Connect. This is located within the
# Apple Developer portal under the "Membership" tab where it shows the "Team Name".

  CLIENT_TEAM_NAME = "{PLACEHOLDER}" # e.g. "REDACTED"

# The team ID for the client's Apple Developer Portal. This is explicitly required when
# using multiple teams for a project. Since REDACTED's projects tend to be distributed and
# tested internally, and subsequently delivered to clients, we use multiple teams. Used by the
# 'Match' tool for syncing/repairing/replacing certificates stored in 'CERTS_REPO' with those
# stored in the Apple Developer Portal associated with this team.

  CLIENT_TEAM_ID = "{PLACEHOLDER}" # e.g. "REDACTED"

# The bundle ID of the application. This is used to create app records in the clients's Apple
# Developer Portal and sync provisioning/code signing for said application. We also use this value
# to set the arbitrary SKU value required when creating app records. This is located in the client's
# Apple Developer portal under "Certificates, Identifiers & Profiles" > "Identifiers" > "App IDs" >
# the value under the "ID" column for the app.

  CLIENT_APP_ID = "{PLACEHOLDER}" # e.g. "com.ClientCompany.coolproject"

# Simply the name of the application. You could specify an app name for distribution internally
# through REDACTED's account for testing that is different than the app name distributed
# to the client. If the client already has an application live on the App Store than the name of
# the app will be located in the App section of their iTunes Connect account.

  CLIENT_APP_NAME = "{PLACEHOLDER}" # e.g. "Cool Project"

# The scheme of the app to build and archive for distribution. If you don't have any custom schemes
# then it's the name of the application.

  CLIENT_SCHEME = "{PLACEHOLDER}" # e.g. "Cool Project Client Release"

# Post an optional message to a Slack channel via an incoming web hook. Go to REDACTED's hooks:
# https://REDACTED
# Add a configuration to post to a certain channel and add the URL string here. Calls to the 'Slack'
# tool will use this environment variable.

# Currently set to post to the channel #fastlane-test. Leave alone and check this channel if you
# want to test and see if it works properly before changing to your project's channel.
# e.g. https://hooks.slack.com/services/{etc}

  ENV["SLACK_URL"] = "REDACTED"

#####################################################################################################
#####################################################################################################
#####################################################################################################
#####################################################################################################
#####################################################################################################
# ---------------------------------------------------------------------------------------------------
# ***************************************** FASTLANE LANES ******************************************
# ---------------------------------------------------------------------------------------------------
#####################################################################################################
#####################################################################################################
#####################################################################################################
#####################################################################################################
#####################################################################################################

# Use this lane for creating the initial app id and record in REDACTED's associated accounts.
# This step is required before any 'Match' commands and before any development/distribution provisioning
# can occur internally via REDACTED's accounts.

  desc "Create the App ID on REDACTED's Apple Dev Portal and app record on REDACTED's iTC."
  lane :produce_internal do

    produce(
      username: INTERNAL_USERNAME,
      team_name: INTERNAL_TEAM_NAME,
      itc_team_name: INTERNAL_TEAM_NAME,
      app_identifier: INTERNAL_APP_ID,
      sku: INTERNAL_APP_ID,
      app_name: INTERNAL_APP_NAME,
      app_version: "0.1" # Initial version number (arbitrary)
    )
  end

# Use this lane for creating the initial app id and record in the client's associated accounts.
# This step is required before any 'Match' commands and before any development/distribution provisioning
# can occur.

  desc "Create the App ID on the client's Apple Dev Portal and app record on the client's iTC."
  lane :produce_client do

    produce(
      username: CLIENT_USERNAME,
      team_name: CLIENT_TEAM_NAME,
      itc_team_name: CLIENT_TEAM_NAME,
      app_identifier: CLIENT_APP_ID,
      sku: CLIENT_APP_ID,
      app_name: CLIENT_APP_NAME,
      app_version: "1.0" # Initial version number (arbitrary)
    )
  end

# Use this lane for syncing REDACTED's development certificates and provisioning to be able to
# run the app on a physical device. Note: Within Xcode you will need to "signing" to manual in the
# project's settings under the "info" tab. Once this lane has ran, you will see the provisioning
# profile as an option within Xcode to select.

  desc "Sync REDACTED's development certificate and code signing to run app on a device locally."
  lane :sync_internal_development do

    match(
      type: "development",
      git_url: CERTS_REPO,
      git_branch: CERTS_INTERNAL_BRANCH,
      app_identifier: INTERNAL_APP_ID,
      username: INTERNAL_USERNAME,
      team_id: INTERNAL_TEAM_ID
    )

    slack(
      message: "Attention: New developer has synced development certificates and code signing for project.",
      default_payloads: []
    )
  end

  lane :get_version_string do
    version = get_info_plist_value(path: "./MicroPayments/Info.plist", key: "CFBundleShortVersionString")
    build = get_info_plist_value(path: "./MicroPayments/Info.plist", key: "CFBundleVersion")
    string = version + "(" + build + ")"
  end

  lane :add_badge_to_app do
    label = "Version-" + get_version_string() + "-blue"
    appicon(appicon_image_file: '../assets/app_icon.png',
              appicon_devices: [:ipad, :iphone, :ios_marketing],
              appicon_path: 'MicroPayments/Images.xcassets'
            )
    add_badge(shield: label)
  end

# Use this lane for distributing a build to REDACTED's Fabric account. This lane performs multiple
# tasks, including creating/syncing adhoc certificates and code signing for the project through
# REDACTED's account, building the app using the provided internal scheme, uploading the build
# to REDACTED's Fabric Beta account, and notifying Slack if/when these tasks are completed.

  desc "Distribute a new build through REDACTED's Fabric account."
  lane :ship_internal_fabric do
    git_pull
    prepare_new_build

    match(
      type: "adhoc",
      git_url: CERTS_REPO,
      git_branch: CERTS_INTERNAL_BRANCH,
      app_identifier: INTERNAL_APP_ID,
      username: INTERNAL_USERNAME,
      team_id: INTERNAL_TEAM_ID
    )

    gym(
      scheme: INTERNAL_SCHEME,
      export_method: "ad-hoc"
    )

    crashlytics(
      api_token: FABRIC_API_KEY,
      build_secret: FABRIC_BUILD_SECRET,
      notifications: true,
      groups: ["REDACTED-int", "REDACTED-qa"]
    )

    slack(
      message: "Attention: Version " + get_version_string() + " of MicroPayments iOS has been distributed through REDACTED's Fabric account.",
      default_payloads: []
    )

    git_commit(path: "./", message: "iOS Version " + get_version_string())
    push_to_git_remote(
      remote: "origin",
      remote_branch: "develop"
    )
  end

# Use this lane for distributing a build to Testflight via REDACTED's iTunes Connect account.
# This lane performs multiple tasks, including creating/syncing app store certificates and code
# signing for the project through REDACTED's account, building the app using the provided
# internal scheme, uploading the build to REDACTED's iTC account, and notifying Slack if/when
# these tasks are completed.

  desc "Distribute a new build via Testflight through REDACTED's iTunes Connect account."
  lane :ship_internal_testflight do

    match(
      type: "appstore",
      git_url: CERTS_REPO,
      git_branch: CERTS_INTERNAL_BRANCH,
      app_identifier: INTERNAL_APP_ID,
      username: INTERNAL_USERNAME,
      team_id: INTERNAL_TEAM_ID
    )

    gym(
      scheme: INTERNAL_SCHEME,
      export_method: "app-store"
    )

    testflight(
      team_name: INTERNAL_TEAM_NAME,
      username: INTERNAL_USERNAME,
      skip_waiting_for_build_processing: true
    )

    slack(
      message: "Attention: A new version of the app has been distributed through REDACTED's Testflight account.",
      default_payloads: []
    )
  end

# Use this lane for distributing a build to Testflight via the client's iTunes Connect account.
# This lane performs multiple tasks, including creating/syncing app store certificates and code
# signing for the project through REDACTED's account, building the app using the provided
# internal scheme, uploading the build to REDACTED's iTC account, and notifying Slack if/when
# these tasks are completed.

  desc "Distribute a new build via Testflight through the client's iTunes Connect account."
  lane :ship_client_testflight do

    match(
      type: "appstore",
      git_url: CERTS_REPO,
      git_branch: CERTS_CLIENT_BRANCH,
      app_identifier: CLIENT_APP_ID,
      username: CLIENT_USERNAME,
      team_id: CLIENT_TEAM_ID
    )

    gym(
      scheme: CLIENT_SCHEME,
      export_method: "app-store"
    )

    testflight(
      team_name: CLIENT_TEAM_NAME,
      username: CLIENT_USERNAME,
      skip_waiting_for_build_processing: true
    )

    slack(
      message: "New production app version has shipped to client's Testflight",
      default_payloads: []
    )

    error do |lane, exception|
      slack(message: exception.message, success: false)
    end

  end

  lane :test do
    run_tests(scheme: "MicroPayments",
              devices: ["iPhone 6s"],
              slack_url: ENV["SLACK_URL"])
  end

  lane :prepare_new_build do
    ensure_git_status_clean
    increment_build_number
    add_badge_to_app
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.99.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                  | Version | Update-Status |
| ----------------------- | ------- | ------------- |
| fastlane-plugin-badge   | 1.1.0   | ✅ Up-To-Date  |
| fastlane-plugin-appicon | 0.13.0  | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| terminal-table            | 1.8.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| commander-fastlane        | 4.4.6        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| faraday_middleware        | 0.12.2       |
| simctl                    | 1.6.4        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.21.2       |
| emoji_regex               | 0.1.1        |
| tty-screen                | 0.6.4        |
| faraday                   | 0.15.2       |
| openssl                   | 2.0.5        |
| json                      | 2.1.0        |
| highline                  | 1.7.10       |
| io-console                | 0.4.6        |
| excon                     | 0.62.0       |
| CFPropertyList            | 3.0.0        |
| plist                     | 3.4.0        |
| atomos                    | 0.1.2        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.5        |
| xcodeproj                 | 1.5.9        |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| fastimage                 | 2.1.3        |
| bundler                   | 1.16.0       |
| unicode-display_width     | 1.4.0        |
| curb                      | 0.9.6        |
| badge                     | 0.9.1        |
| fastlane-plugin-badge     | 1.1.0        |
| fastlane-plugin-appicon   | 0.13.0       |
</details>

*generated on:* **2018-07-10**
</details>

**Comment by akwilliamson** [comment]
`update_fastlane` in my fastfile doesn't seem to do anything even though it recognizes Fastlane is out of date and says it updates it to the latest version. However, running `bundle update fastlane` manually seems to update it properly. How do I get this to work with the command in my Fastfile?

**Comment by johnwongapi** [comment]
have you try putting update_fastlane in block of `before_all`?
