### ISSUE TITLE
produce - rewrite for App Store Connect API

### ISSUE THREAD

**Issue by joshdholtz** [fastlane/fastlane#18157]
### Issue Description
`produce` has two parts two it - one for the creation of Developer Portal app and the other for the creation of the App Store Connect API app. The App Store Connect API has been rewritten (for web session since API Key not allowed) but the Developer Portal has not been fully rewritten for App Store Connect API yet. 

### Tasks
- [ ] Find all endpoints that need to be replaced
- [ ] Verify all endpoints are can be at least used by private App Store Connect API
- [ ] Verify all endpoints can be used by API Key
- [ ] Update bundle capabilities to use a `CapabilitySetting` builder (see https://github.com/fastlane/fastlane/pull/18080#discussion_r569159499)

**Comment by mortenholmgaard** [comment]
Any news on this? We are awaiting API key support for produce. (and PEM)

**Comment by Sega-Zero** [comment]
still waiting for API key support

**Comment by mortenholmgaard** [comment]
@joshdholtz Is it possible that this could be prioritised soon? 
We haven't been able to use our CI to deploy to AppStore for months now, because we are awaiting support for API key for produce (and pem)

**Comment by virus2016** [comment]
> @joshdholtz Is it possible that this could be prioritised soon?
> We haven't been able to use our CI to deploy to AppStore for months now, because we are awaiting support for API key for produce (and pem)

You can just create an app in connect then use pem for the push certs locally to get you by.

**Comment by mortenholmgaard** [comment]
@virus2016 Yeah you are right that is possible, but it is definitely not optimale when maintaining a lot of apps! We were used to be able to relay that work to the CI, and we a talking a lot of time when it is with many apps. So yes it is possible, just like it was possible to deploy apps before fastlane, but efficient it isn't. 
Currently we are running our CI lanes locally as that is the only real option, but we have just been expecting this to be done soon after the other parts of fastlane were migrated to API key. We have weekly been monitoring https://docs.fastlane.tools/app-store-connect-api/ to see when the support was there - I just hope it can be prioritized soon.

**Comment by joshdholtz** [comment]
@mortenholmgaard This is waiting on some official App Store Connect API Change (API key auth version) to be pushed. There were some changes to the unofficial version (web auth) but I’m a little hesitant to make changes using that if they aren’t finalized.

I will be on this right away once changes are pushed and there is actually something for me to make changes with 😊

**Comment by jjochen** [comment]
Ping

**Comment by kerrmarin-lvmh** [comment]
Thanks @joshdholtz! Is there a radar we can clone to help put pressure on whatever is blocking this? Or any other way we can help?

**Comment by Sega-Zero** [comment]
still waiting

**Comment by GForceWeb** [comment]
Also waiting

**Comment by Sega-Zero** [comment]
@joshdholtz any news on this?

**Comment by ThomasCle** [comment]
> @mortenholmgaard This is waiting on some official App Store Connect API Change (API key auth version) to be pushed. There were some changes to the unofficial version (web auth) but I’m a little hesitant to make changes using that if they aren’t finalized.
> 
> I will be on this right away once changes are pushed and there is actually something for me to make changes with 😊

@joshdholtz Are we still waiting for the App Store Connect API change? 😢 I'd love to get this fixed soon.

**Comment by Sega-Zero** [comment]
still waiting

**Comment by ThomasCle** [comment]
Still waiting…

**Comment by mortenholmgaard** [comment]
@joshdholtz Any news on this?

**Comment by Sega-Zero** [comment]
we're still waiting

**Comment by jjochen** [comment]
⏳

**Comment by mortenholmgaard** [comment]
Still waiting..

**Comment by AtishaRibeiro** [comment]
@joshdholtz Any update on the App Store Connect API side of things?

**Comment by mohamadrezaahvaraki** [comment]
Any update on the App Store Connect API support for Produce ?

**Comment by Sega-Zero** [comment]
@joshdholtz please, do something. having #29909 and still cannot use new AppStore API

**Comment by tcurdt** [comment]
There is a new kid in town that seems to use the API:

https://github.com/platacard/blimp

So, maybe that could help with the implementation in fastlane?

**Comment by jakerenshawballys** [comment]
> There is a new kid in town that seems to use the API:
> 
> https://github.com/platacard/blimp
> 
> So, maybe that could help with the implementation in fastlane?

@iBotPeaches ?
