### ISSUE TITLE
SimulatorZoomFix: Replace more than just whitespace characters (due to iPad Pro names)

### ISSUE THREAD

**Issue by jdhealy** [fastlane/fastlane#5700]
### Issue Description

An `iphonesimulator` device with name "iPad Pro (9.7 inch)" will (after launch) add a key `SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPad-Pro--9-7-inch-`.

The character replacement last modified in https://github.com/fastlane-old/snapshot/commit/9f0822f69cfca3a4789a60e7d6953d980736ecbc only replaces whitespace.

Presumptively, I was going to make a PR for…
```ruby
simulator_name = simulator.name.tr(
  '^' + # replace all characters except ones included below
  ('a'.upto('z').to_a + 'A'.upto('Z').to_a + '0'.upto('9').to_a).join(''), 
  "-"
)
```

…but, then I launched an "iPad Pro (12.9 inch)" simulator device (with Xcode 8S193k) and a key for `SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPad-Pro` appeared at the bottom of the `dict`, so that's probably too naïve.

### Todo
* [ ] Test older Xcode versions to see if the key for the original 12.9 inch iPad Pro has always been `SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPad-Pro`.
  * [ ] Then, I‘ll write a switch statement, based on findings.
* [ ] Worry about future device names… 😕  

See also: https://github.com/fastlane/fastlane/issues/5673#issuecomment-238973384

**Comment by KrauseFx** [comment]
Interesting - thanks. Do you already know the key we actually have to set, and the key we currently set? This way it's easier for me to fix the bug 👍

**Comment by jdhealy** [comment]
The key which shows up for "iPad Pro (9.7 inch)" after launching the simulator through Xcode (that's how I meant it in the first sentence of the issue — sorry, get how it's vague): `SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPad-Pro--9-7-inch-`.

In the same way: 
> then I launched an "iPad Pro (12.9 inch)" simulator device (with Xcode 8S193k) and a key for `SimulatorWindowLastScale-com.apple.CoreSimulator.SimDeviceType.iPad-Pro` appeared at the bottom of the `dict`

**Comment by TKBurner** [comment]
@jdhealy Thanks for following up. Are you interested in submitting a PR? Either way thanks so much for helping us. Hope you have a wonderful weekend coming up 👍

**Comment by jdhealy** [comment]
> Are you interested in submitting a PR

Yeah, I think I'm almost there with a general solution.

**Comment by KrauseFx** [comment]
Awesome, thanks @jdhealy 👍
