### ISSUE TITLE
[Proposal] Provide easy to remember aliases for all the fastlane tools

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/fastlane#8806]
> http://fastlane.tools 'gym' command seems to always be followed by the comment '# Build your app'. Maybe call it `build` instead of `gym`?

via https://twitter.com/drylight/status/849825043567656961

#### [Proposal] Provide easy to remember aliases for all the fastlane tools

Until a few months ago, _fastlane_ consisted out of lots of different tools and repos, each with a separate, unique name. End of 2016 we unified _fastlane_ to be a mono-repo, making _fastlane_ the main tool. 

Because of that, you still see names like `gym`, `match` and `scan` in your `Fastfile`, which might be confusing to new users. _fastlane_ could offer simpler to remember aliases for built-in tools.

#### Currently
```ruby
lane :beta do
  scan
  match
  gym
  pilot  
end
```

#### Proposed future
```ruby
lane :beta do
  ios_tests
  setup_codesigning
  ios_build
  testflight  
end
```

Don’t worry, the names some of you know and love will live on, we just want to make it easier for newcomers. Everything will be fully backwards-compatible.

#### Things to consider
- [ ] We still have config files like the `Gymfile` and `Matchfile`
- [ ] Are aliases confusing as there are now multiple ways of doing the same thing?

#### Tasks to implement this:
- [ ] Add aliases for all the actions (there is now official aliases feature built-in, so we don't have to do what we've done with `actions/testflight.rb`)
- [ ] Update docs.fastlane.tools to use the new aliases
- [ ] Update fastlane.tools to be simpler
- [ ] Update `enhancer` or `tool_collector` to consolidate aliases to properly track the crash rate still

**Comment by ohayon** [comment]
I wonder if we could make this even smarter, so that the future could look more like:
```
lane :beta do
  run_tests
  setup_codesigning
  build
  testflight
end
```

and then we can figure out which action/tool to run based on the platform of the lane.

**Comment by KrauseFx** [comment]
@ohayon I was thinking about the same thing, however many people use their `Fastfile` without platform lanes, and therefore would be confused when copying a lane implementation from somewhere and it doesn't work.

**Comment by lwdupont** [comment]
I'm always for making things easy to read without documentation. More straightforward names would help a lot. Thanks for all the work on these though :)

**Comment by Montoya** [comment]
Voted :+1: because it's one less thing to worry about when learning fastlane and would hopefully boost adoption

**Comment by lappp9** [comment]
Yeah, I voted 👍 just because there was that little bit of extra mental overhead of sitting and thinking "what does 'match' imply again?....oh yeah" and then moving on.  I personally like the names but think the more explanatory ones are probably better for getting people into using it.

**Comment by SpacyRicochet** [comment]
Voted 👍 since this would help clarify what's happening in a lane for people new to fastlane.

**Comment by NSCabezon** [comment]
they're cool names! But it will help people to get to know the tools so I guess 👍🏼

**Comment by reidmain** [comment]
Exactly what @lappp9 said. Making it so that the Fastfile is human readable and has no ambiguity would be awesome. I would love it for some of our infrastructure devs to be able to read the file without asking me what "gym" is.

**Comment by mwfire** [comment]
I'd like to make a case here for sigh not being renamed. It is and will be self-explanatory for everyone having to deal with provisioning ;)

**Comment by philikon** [comment]
The names are cute at first, but I agree on the mental overhead. Plus, at this point gym/sigh/match/scan/pilot/etc. are the odd ones out among all the other commands that have descriptive names. Time to make them aliases to more descriptive commands that stick around for backwards compatibility only.

**Comment by rolandleth** [comment]
While it's nice (and cute, as @philikon said) to have custom names, it's much nicer to know at a glance what functions they fulfil, and to not have to memorise so many of them; much easier to get newcomers on board, as well.

**Comment by Makazone** [comment]
Voted 👍. My first thought was "No way! These names is what makes fastlane - Fastlane!". Than I read the comments and agreed, people outside of community might have hard time onboarding due to naming. 

However, I should say that at least I rarely find myself doing just gym, or just sigh. It's always a combination of different flags, configurations and schemes, so I have private lanes for signing, bundling and distributing which have proper names that describe a step, such as code_sign. In that set up I like to think of sigh/match just being atomic units that could not be used on their own, rather accompanied by a set of flags / ifs etc. Given that, would be weird to have a lane called code_sign_project that calls something like code_signing instead of match/sigh.

Overall, renaming is a controversial topic. We all remember Grand Renaming from Apple. But making fastlane accessible for everyone is a bigger idea, so I say yes to more clear names.

**Comment by alper** [comment]
Lots of open source projects suffer from having started with an unfortunate set of names/concepts and never changing that because of inertia. I'd welcome this effort to fix that.

> We still have config files like the Gymfile and Matchfile

Those should be renamed too.

> Are aliases confusing as there are now multiple ways of doing the same thing?

There should be only one way to do something while the other stuff should still work for backwards compatibility it should be forgotten and people should be encouraged to convert their steps.

**Comment by orta** [comment]
> I was thinking about the same thing, however many people use their Fastfile without platform lanes, and therefore would be confused when copying a lane implementation from somewhere and it doesn't work.

This can be figured out/inferred pretty quickly with a check for "**/*.xcodeproj" or "**/build.gradle". Failing if neither or both are found.

**Comment by xaverlohmueller** [comment]
While I'm sure the proposed names will make it easier for beginners to find out what the actions do, I find the current names like `gym` far easier to remember than a generic `iOS_build`. Or was it `build_iOS`? `build_app`?

**Comment by mfurtak** [comment]
One more thing to consider is that we currently allow direct tool invocation from the command line (e.g. `fastlane snapshot`)

In addition to having aliases for action names (as used inside `Fastfile`s), we'd have to have those same aliases for tool names as processed by _fastlane_ there.

**Comment by dineshrajas** [comment]
I upvoted because that makes easy for newbies to jump into integration without thinking more about what is what.

But, instead of specifying the platform name in each command, we can put that in lane name. Something like below.

```
lane :ios.beta do
  test
  codesign
  build
  testflight
end
```
```
lane :android.production do
  test
  build
  playstore
end
```
If we are able to automate cross checking commands against the platform name, that would be great. Not sure, how this will work out.

**Comment by KrauseFx** [comment]
@dineshrajas thanks for the feedback. We already have `platform` blocks that could help with that, see https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md for more information. We could easily use them, however currently not all _fastlane_ setups have them in their `Fastfile`

**Comment by doozMen** [comment]
👌🏻👍🏻please do! I understand the history but it is better to be clear.

**Comment by KrauseFx** [comment]
Let's leave this open for now actually

**Comment by KrauseFx** [comment]
Big shoutout to @mpirri for finishing this project and launching it today 🚀 https://github.com/fastlane/fastlane/pull/10939
